jobs:
  autoTestPR:
    if: startsWith(github.event.comment.body, 'auto exclude test')
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Set up Python 3.8
      uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
      with:
        python-version: 3.8
    - continue-on-error: true
      name: check python version
      run: 'python -V

        '
    - continue-on-error: true
      name: install xml module
      run: 'pip install lxml

        '
    - continue-on-error: true
      name: checkout current repo
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      with:
        path: tests
    - continue-on-error: true
      name: checkout TKG repo
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      with:
        path: TKG
        ref: master
        repository: adoptium/TKG.git
    - continue-on-error: true
      env:
        comment_body: ${{ github.event.comment.body }}
      name: run script
      run: 'git config --list

        python TKG/scripts/testBot/disable.py -m "$comment_body" -c "${{ github.event.comment.html_url
        }}" -d "$GITHUB_WORKSPACE/tests"

        '
    - continue-on-error: true
      if: failure()
      name: test cannot be found
      run: 'curl -u github-actions:${{ secrets.GITHUB_TOKEN }} -d ''{ "body":  "The
        specified test cannot be excluded. Action run: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
        }'' -X POST ${{ github.event.issue.comments_url }}

        '
    - continue-on-error: true
      name: Create Pull Request
      uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38
      with:
        body: 'related: ${{ github.event.comment.html_url }}

          triggered by @${{ github.event.comment.user.login }}

          [ci skip]

          '
        branch: autoTestPR
        branch-suffix: random
        commit-message: 'AUTO: ${{ github.event.comment.body }}

          - related: ${{ github.event.comment.html_url }}

          '
        path: tests
        signoff: 'true'
        title: ${{ github.event.comment.body }}
    - continue-on-error: true
      name: add label
      run: curl -u github-actions:${{ secrets.GITHUB_TOKEN }} -d '{"labels":["test
        excluded"]}' -X POST ${{ github.event.issue.url }}/labels
name: Auto test PR
on:
  repository_dispatch:
    types: trigger-ga___autoTestPR.yml
