jobs:
  rmAutoTestPRBranch:
    if: startsWith(github.event.pull_request.title, 'auto exclude test') && startsWith(github.event.pull_request.head.ref,
      'autoTestPR') && (github.event.pull_request.user.login == 'github-actions[bot]')
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: remove auto test PR branch when the PR is closed
      run: curl -u github-actions:${{ secrets.GITHUB_TOKEN }} -X DELETE ${{ github.event.pull_request.head.repo.url
        }}/git/refs/heads/${{ github.event.pull_request.head.ref }}
name: Remove autoTestPR branch
on:
  repository_dispatch:
    types: trigger-ga___rmAutoTestPRBranch.yml
